apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-postgres-config
data:
  POSTGRES_USER: {{ .Values.postgres.config.POSTGRES_USER }}
  POSTGRES_DB: {{ .Values.postgres.config.POSTGRES_DB }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.config.POSTGRES_PASSWORD | b64enc }}