# templates/postgres.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-postgres-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: {{ .Values.postgres.volume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgres.volume.path }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-postgres-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-postgres-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Chart.Name }}-postgres-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-postgres-config
                key: POSTGRES_DB
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  clusterIP: None