apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-app
  template:
    metadata:
      labels:
        app: registration-app
    spec:
      containers:
      - name: registration-app
        image: masum012924/registration-app:v2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: registration-app-service
spec:
  selector:
    app: registration-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
